<#
.SYNOPSIS
  Sync the CANONICAL AI briefing file to all agent-specific mirrors in one shot.

.DESCRIPTION
  The ONLY file you ever edit manually is:
      .obsidian-vault/CLAUDE.md

  After editing it, run THIS script to push the content out to every
  mirror file that AI agents auto-load (project-root CLAUDE.md,
  .cursorrules, .windsurfrules, .github/copilot-instructions.md,
  and the vault-level generic aliases AGENT.md + AI_BRIEFING.md).

  Every mirror gets a prominent "DO NOT EDIT THIS FILE" warning header
  so you (and the AI) never accidentally edit a mirror instead of the
  canonical source.

  Run from the PROJECT ROOT folder:
      PowerShell>  & .\sync-agent-briefings.ps1

  If you get a ExecutionPolicy warning, run once:
      Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
  Then re-run the script.

.NOTES
  Author : Universal Second Brain Project Template
  Version: 1.0
#>

# ============================================================================
# 1. Setup — resolve paths relative to the PROJECT ROOT
#    (Script must be placed at the project root for this to work.)
# ============================================================================
$ErrorActionPreference = 'Stop'

$Root          = Split-Path -Parent $MyInvocation.MyCommand.Path
$CanonicalRel  = Join-Path '.obsidian-vault' 'CLAUDE.md'
$CanonicalPath = Join-Path $Root $CanonicalRel

if (-not (Test-Path $CanonicalPath)) {
    Write-Error "ERROR: Canonical source not found at: $CanonicalRel"
    Write-Error "Run this script from the PROJECT ROOT folder only."
    exit 1
}

# Read the CANONICAL content ONCE — this is our source of truth.
$Raw = Get-Content -LiteralPath $CanonicalPath -Raw -Encoding UTF8

# ============================================================================
# 2. Helper: Build the appropriate warning header for each mirror type
# ============================================================================
function Get-WarningHeader {
    param(
        [Parameter(Mandatory=$true)] [string] $MirrorName,
        [Parameter(Mandatory=$true)] [string] $Purpose,
        [Parameter(Mandatory=$true)] [bool]   $MarkdownStyle = $true
    )

    if ($MarkdownStyle) {
        # Standard HTML comment header for Markdown / .md / copilot-instructions.md files
        @"
<!--
  ⚠️  DO NOT EDIT THIS FILE DIRECTLY. AUTOMATICALLY GENERATED MIRROR.

  $Purpose

  Canonical source: .obsidian-vault/CLAUDE.md  (edit ONLY that file)
  Sync command:     & .\sync-agent-briefings.ps1
-->

"@
    }
    else {
        # Hash-comment style for .cursorrules / .windsurfrules / YAML-style files
        @"
# ⚠️  DO NOT EDIT THIS FILE DIRECTLY. AUTOMATICALLY GENERATED MIRROR.
#
# $Purpose
#
# Canonical source: .obsidian-vault/CLAUDE.md  (edit ONLY that file)
# Sync command:     & .\sync-agent-briefings.ps1

"@
    }
}

# ============================================================================
# 3. Define every mirror we maintain
#    (Add new entries here to support new AI agent conventions.)
# ============================================================================
$Mirrors = @(
    # ---------- PROJECT ROOT — native agent conventions -------------------
    @{
        Rel           = 'CLAUDE.md'
        Purpose       = 'Claude Code CLI by Anthropic auto-loads ./CLAUDE.md from the launch directory. It does not scan subfolders, so this root mirror must exist.'
        StyleMd       = $true
        PrependBanner = $false   # mirrors already have their own header
    },
    @{
        Rel           = '.cursorrules'
        Purpose       = 'Cursor IDE by Anysphere reads .cursorrules at project root as its NATIVE rules file. Loaded first — before any code context.'
        StyleMd       = $false
        PrependBanner = $false
    },
    @{
        Rel           = '.windsurfrules'
        Purpose       = 'Windsurf IDE by Codeium (Cascade) reads .windsurfrules at project root as its NATIVE rules file.'
        StyleMd       = $false
        PrependBanner = $false
    },
    @{
        Rel           = (Join-Path '.github' 'copilot-instructions.md')
        Purpose       = 'GitHub Copilot Agent (VS Code / github.dev) recognizes .github/copilot-instructions.md at project root as its NATIVE project-level briefing. Loaded preferentially.'
        StyleMd       = $true
        PrependBanner = $false
    },
    # ---------- OBSIDIAN VAULT — generic search aliases -------------------
    @{
        Rel           = (Join-Path '.obsidian-vault' 'AGENT.md')
        Purpose       = 'Generic alias mirror so any future/unknown AI agent that does semantic search for the KEYWORD "agent" ranks the project briefing highly.'
        StyleMd       = $true
        PrependBanner = $false
    },
    @{
        Rel           = (Join-Path '.obsidian-vault' 'AI_BRIEFING.md')
        Purpose       = 'Generic alias mirror so any future/unknown AI agent that does semantic search for the KEYWORD "briefing" ranks the project briefing highly.'
        StyleMd       = $true
        PrependBanner = $false
    }
)

# ============================================================================
# 4. Write every mirror
# ============================================================================
$CreatedDirs = 0
$Written      = 0

foreach ($m in $Mirrors) {
    $DestPath = Join-Path $Root $m.Rel

    # Ensure parent directory exists (for .github/, .vscode/, etc.)
    $DestDir = Split-Path -Parent $DestPath
    if ($DestDir -and -not (Test-Path -LiteralPath $DestDir)) {
        New-Item -ItemType Directory -Path $DestDir -Force | Out-Null
        $CreatedDirs++
    }

    $Header  = Get-WarningHeader -MirrorName (Split-Path -Leaf $DestPath) `
                                  -Purpose    $m.Purpose `
                                  -MarkdownStyle:$m.StyleMd

    $FinalContent = $Header + $Raw

    Set-Content -LiteralPath $DestPath -Value $FinalContent -NoNewline -Encoding UTF8
    $Written++

    Write-Host "  [OK] Synced  ->  $($m.Rel)"
}

# ============================================================================
# 5. Final report
# ============================================================================
Write-Host ""
Write-Host "==============================================================="
Write-Host "  [DONE] sync-agent-briefings.ps1 - complete"
Write-Host "==============================================================="
Write-Host "  Canonical source : .obsidian-vault/CLAUDE.md"
Write-Host "  Mirrors updated  : $Written"
Write-Host "  Dirs created     : $CreatedDirs"
Write-Host ""
Write-Host "  Next step: commit code + vault + mirrors together in Git."
Write-Host ""
